export const MARK_ATTENDANCE_REQUEST = "MARK_ATTENDANCE_REQUEST";
export const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
export const MARK_ATTENDANCE_FAIL = "MARK_ATTENDANCE_FAIL";

export const DONE_ATTENDANCE_REQUEST = "DONE_ATTENDANCE_REQUEST";
export const DONE_ATTENDANCE_SUCCESS = "DONE_ATTENDANCE_SUCCESS";
export const DONE_ATTENDANCE_FAIL = "DONE_ATTENDANCE_FAIL";


export const MONTHLY_ATTENDANCE_REQUEST = "MONTHLY_ATTENDANCE_REQUEST";
export const MONTHLY__ATTENDANCE_SUCCESS = "MONTHLY_ATTENDANCE_SUCCESS";
export const MONTHLY__ATTENDANCE_FAIL = "MONTHLY_ATTENDANCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
