export const ALL_ENQUIRY_REQUEST = "ALL_ENQUIRY_REQUEST";
export const ALL_ENQUIRY_SUCCESS = "ALL_ENQUIRY_SUCCESS";
export const ALL_ENQUIRY_FAIL = "ALL_ENQUIRY_FAIL";

export const FILTER_ENQUIRY_REQUEST = "FILTER__ENQUIRY_REQUEST";
export const FILTER__ENQUIRY_SUCCESS = "FILTER__ENQUIRY_SUCCESS";
export const FILTER__ENQUIRY_FAIL = "FILTER__ENQUIRY_FAIL";

export const ADD_ENQUIRY_REQUEST = "ADD_ENQUIRY_REQUEST";
export const ADD_ENQUIRY_SUCCESS = "ADD_ENQUIRY_SUCCESS";
export const ADD_ENQUIRY_FAIL = "ADD_ENQUIRY_FAIL";

export const DELETE_ENQUIRY_REQUEST = "DELETE_ENQUIRY_REQUEST";
export const DELETE_ENQUIRY_SUCCESS = "DELETE_ENQUIRY_SUCCESS";
export const DELETE_ENQUIRY_FAIL = "DELETE_ENQUIRY_FAIL";

export const UPDATE_ENQUIRY_REQUEST = "UPDATE_ENQUIRY_REQUEST";
export const UPDATE_ENQUIRY_SUCCESS = "UPDATE_ENQUIRY_SUCCESS";
export const UPDATE_ENQUIRY_FAIL = "UPDATE_ENQUIRY_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_RESET_PROFILE_SUCCESS = "UPDATE_RESET_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";