export const ALL_COLLEGE_REQUEST = "ALL_COLLEGE_REQUEST";
export const ALL_COLLEGE_SUCCESS = "ALL_COLLEGE_SUCCESS";
export const ALL_COLLEGE_FAIL = "ALL_COLLEGE_FAIL";

export const ALL_SCHOOL_REQUEST = "ALL_SCHOOL_REQUEST";
export const ALL_SCHOOL_SUCCESS = "ALL_SCHOOL_SUCCESS";
export const ALL_SCHOOL_FAIL = "ALL_SCHOOL_FAIL";

export const ALL_COACHING_REQUEST = "ALL_COACHING_REQUEST";
export const ALL_COACHING_SUCCESS = "ALL_COACHING_SUCCESS";
export const ALL_COACHING_FAIL = "ALL_COACHING_FAIL";

export const ALL_CLIENT_REQUEST = "ALL_CLIENT_REQUEST";
export const ALL_CLIENT_SUCCESS = "ALL_CLIENT_SUCCESS";
export const ALL_CLIENT_FAIL = "ALL_CLIENT_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const ADD_BATCH_REQUEST = "ADD_BATCH_REQUEST";
export const ADD_BATCH_SUCCESS = "ADD_BATCH_SUCCESS";
export const ADD_BATCH_FAIL = "ADD_BATCH_FAIL";

export const UPDATE_BATCH_REQUEST = "UPDATE_BATCH_REQUEST";
export const UPDATE_BATCH_SUCCESS = "UPDATE_BATCH_SUCCESS";
export const UPDATE_BATCH_FAIL = "UPDATE_BATCH_FAIL";

export const ALL_BATCH_REQUEST = " ALL_BATCH_REQUEST";
export const ALL_BATCH_SUCCESS = " ALL_BATCH_SUCCESS";
export const ALL_BATCH_FAIL = " ALL_BATCH_FAIL";

export const DELETE_BATCH_REQUEST = "DELETE_BATCH_REQUEST";
export const DELETE_BATCH_SUCCESS = "DELETE_BATCH_SUCCESS";
export const DELETE_BATCH_FAIL = "DELETE_BATCH_FAIL";

export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";

export const ALL_COURSE_REQUEST = " ALL_COURSE_REQUEST";
export const ALL_COURSE_SUCCESS = " ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAIL = " ALL_COURSE_FAIL";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const ALL_CATEGORY_REQUEST = " ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = " ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = " ALL_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const ADD_FEESTRUCTURE_REQUEST = "ADD_FEESTRUCTURE_REQUEST";
export const ADD_FEESTRUCTURE_SUCCESS = "ADD_FEESTRUCTURE_SUCCESS";
export const ADD_FEESTRUCTURE_FAIL = "ADD_FEESTRUCTURE_FAIL";

export const UPDATE_FEESTRUCTURE_REQUEST = "UPDATE_FEESTRUCTURE_REQUEST";
export const UPDATE_FEESTRUCTURE_SUCCESS = "UPDATE_FEESTRUCTURE_SUCCESS";
export const UPDATE_FEESTRUCTURE_FAIL = "UPDATE_FEESTRUCTURE_FAIL";

export const ALL_FEESTRUCTURE_REQUEST = " ALL_FEESTRUCTURE_REQUEST";
export const ALL_FEESTRUCTURE_SUCCESS = " ALL_FEESTRUCTURE_SUCCESS";
export const ALL_FEESTRUCTURE_FAIL = " ALL_FEESTRUCTURE_FAIL";

export const DELETE_FEESTRUCTURE_REQUEST = "DELETE_FEESTRUCTURE_REQUEST";
export const DELETE_FEESTRUCTURE_SUCCESS = "DELETE_FEESTRUCTURE_SUCCESS";
export const DELETE_FEESTRUCTURE_FAIL = "DELETE_FEESTRUCTURE_FAIL";

export const ADD_EMPLOYEETYPE_REQUEST = "ADD_EMPLOYEETYPE_REQUEST";
export const ADD_EMPLOYEETYPE_SUCCESS = "ADD_EMPLOYEETYPE_SUCCESS";
export const ADD_EMPLOYEETYPE_FAIL = "ADD_EMPLOYEETYPE_FAIL";

export const UPDATE_EMPLOYEETYPE_REQUEST = "UPDATE_EMPLOYEETYPE_REQUEST";
export const UPDATE_EMPLOYEETYPE_SUCCESS = "UPDATE_EMPLOYEETYPE_SUCCESS";
export const UPDATE_EMPLOYEETYPE_FAIL = "UPDATE_EMPLOYEETYPE_FAIL";

export const ALL_EMPLOYEETYPE_REQUEST = " ALL_EMPLOYEETYPE_REQUEST";
export const ALL_EMPLOYEETYPE_SUCCESS = " ALL_EMPLOYEETYPE_SUCCESS";
export const ALL_EMPLOYEETYPE_FAIL = " ALL_EMPLOYEETYPE_FAIL";

export const DELETE_EMPLOYEETYPE_REQUEST = "DELETE_EMPLOYEETYPE_REQUEST";
export const DELETE_EMPLOYEETYPE_SUCCESS = "DELETE_EMPLOYEETYPE_SUCCESS";
export const DELETE_EMPLOYEETYPE_FAIL = "DELETE_EMPLOYEETYPE_FAIL";

export const ADD_BRANCH_REQUEST = "ADD_BRANCH_REQUEST";
export const ADD_BRANCH_SUCCESS = "ADD_BRANCH_SUCCESS";
export const ADD_BRANCH_FAIL = "ADD_BRANCH_FAIL";

export const UPDATE_BRANCH_REQUEST = "UPDATE_BRANCH_REQUEST";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAIL = "UPDATE_BRANCH_FAIL";

export const ALL_BRANCH_REQUEST = " ALL_BRANCH_REQUEST";
export const ALL_BRANCH_SUCCESS = " ALL_BRANCH_SUCCESS";
export const ALL_BRANCH_FAIL = " ALL_BRANCH_FAIL";

export const DELETE_BRANCH_REQUEST = "DELETE_BRANCH_REQUEST";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAIL = "DELETE_BRANCH_FAIL";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_RESET = "ADD_STUDENT_RESET";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";

export const ALL_STUDENT_REQUEST = " ALL_STUDENT_REQUEST";
export const ALL_STUDENT_SUCCESS = " ALL_STUDENT_SUCCESS";
export const ALL_STUDENT_FAIL = " ALL_STUDENT_FAIL";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";

export const ADD_Designation_REQUEST = "ADD_Designation_REQUEST";
export const ADD_Designation_SUCCESS = "ADD_Designation_SUCCESS";
export const ADD_Designation_RESET = "ADD_Designation_RESET";
export const ADD_Designation_FAIL = "ADD_Designation_FAIL";

export const UPDATE_Designation_REQUEST = "UPDATE_Designation_REQUEST";
export const UPDATE_Designation_SUCCESS = "UPDATE_Designation_SUCCESS";
export const UPDATE_Designation_FAIL = "UPDATE_Designation_FAIL";

export const ALL_Designation_REQUEST = " ALL_Designation_REQUEST";
export const ALL_Designation_SUCCESS = " ALL_Designation_SUCCESS";
export const ALL_Designation_FAIL = " ALL_Designation_FAIL";

export const DELETE_Designation_REQUEST = "DELETE_Designation_REQUEST";
export const DELETE_Designation_SUCCESS = "DELETE_Designation_SUCCESS";
export const DELETE_Designation_FAIL = "DELETE_Designation_FAIL";

export const ADD_Department_REQUEST = "ADD_Department_REQUEST";
export const ADD_Department_SUCCESS = "ADD_Department_SUCCESS";
export const ADD_Department_RESET = "ADD_Department_RESET";
export const ADD_Department_FAIL = "ADD_Department_FAIL";

export const UPDATE_Department_REQUEST = "UPDATE_Department_REQUEST";
export const UPDATE_Department_SUCCESS = "UPDATE_Department_SUCCESS";
export const UPDATE_Department_FAIL = "UPDATE_Department_FAIL";

export const ALL_Department_REQUEST = " ALL_Department_REQUEST";
export const ALL_Department_SUCCESS = " ALL_Department_SUCCESS";
export const ALL_Department_FAIL = " ALL_Department_FAIL";

export const DELETE_Department_REQUEST = "DELETE_Department_REQUEST";
export const DELETE_Department_SUCCESS = "DELETE_Department_SUCCESS";
export const DELETE_Department_FAIL = "DELETE_Department_FAIL";

export const ADD_CourseDuration_REQUEST = "ADD_CourseDuration_REQUEST";
export const ADD_CourseDuration_SUCCESS = "ADD_CourseDuration_SUCCESS";
export const ADD_CourseDuration_RESET = "ADD_CourseDuration_RESET";
export const ADD_CourseDuration_FAIL = "ADD_CourseDuration_FAIL";

export const UPDATE_CourseDuration_REQUEST = "UPDATE_CourseDuration_REQUEST";
export const UPDATE_CourseDuration_SUCCESS = "UPDATE_CourseDuration_SUCCESS";
export const UPDATE_CourseDuration_FAIL = "UPDATE_CourseDuration_FAIL";

export const ALL_CourseDuration_REQUEST = " ALL_CourseDuration_REQUEST";
export const ALL_CourseDuration_SUCCESS = " ALL_CourseDuration_SUCCESS";
export const ALL_CourseDuration_FAIL = " ALL_CourseDuration_FAIL";

export const DELETE_CourseDuration_REQUEST = "DELETE_CourseDuration_REQUEST";
export const DELETE_CourseDuration_SUCCESS = "DELETE_CourseDuration_SUCCESS";
export const DELETE_CourseDuration_FAIL = "DELETE_CourseDuration_FAIL";

export const ADD_TEST_REQUEST = "ADD_TEST_REQUEST";
export const ADD_TEST_SUCCESS = "ADD_TEST_SUCCESS";
export const ADD_TEST_RESET = "ADD_TEST_RESET";
export const ADD_TEST_FAIL = "ADD_TEST_FAIL";

export const UPDATE_TEST_REQUEST = "UPDATE_TEST_REQUEST";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";
export const UPDATE_TEST_FAIL = "UPDATE_TEST_FAIL";

export const ALL_TEST_REQUEST = " ALL_TEST_REQUEST";
export const ALL_TEST_SUCCESS = " ALL_TEST_SUCCESS";
export const ALL_TEST_FAIL = " ALL_TEST_FAIL";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAIL = "DELETE_TEST_FAIL";

export const UPDATE_CREDENTIALS_REQUEST = "UPDATE_CREDENTIALS_REQUEST";
export const UPDATE_CREDENTIALS_SUCCESS = "UPDATE_CREDENTIALS_SUCCESS";
export const UPDATE_CREDENTIALS_RESET_SUCCESS =
  "UPDATE_CREDENTIALS_RESET_SUCCESS";
export const UPDATE_CREDENTIALS_FAIL = "UPDATE_CREDENTIALS_FAIL";

export const ALL_STUDENT_TEST_REQUEST = " ALL_TEST_REQUEST";
export const ALL_STUDENT_TEST_SUCCESS = " ALL_TEST_SUCCESS";
export const ALL_STUDENT_TEST_FAIL = " ALL_TEST_FAIL";

export const UPDATE_STUDENT_TEST_REQUEST = "UPDATE_STUDENT_TEST_REQUEST";
export const UPDATE_STUDENT_TEST_SUCCESS = "UPDATE_STUDENT_TEST_SUCCESS";
export const UPDATE_STUDENT_TEST_RESET_SUCCESS =
  "UPDATE_STUDENT_TEST_RESET_SUCCESS";
export const UPDATE_STUDENT_TEST_FAIL = "UPDATE_STUDENT_TEST_FAIL";

export const ADD_RECEIPTPREFIX_REQUEST = "ADD_RECEIPTPREFIX_REQUEST";
export const ADD_RECEIPTPREFIX_SUCCESS = "ADD_RECEIPTPREFIX_SUCCESS";
export const ADD_RECEIPTPREFIX_FAIL = "ADD_RECEIPTPREFIX_FAIL";

export const UPDATE_RECEIPTPREFIX_REQUEST = "UPDATE_RECEIPTPREFIX_REQUEST";
export const UPDATE_RECEIPTPREFIX_SUCCESS = "UPDATE_RECEIPTPREFIX_SUCCESS";
export const UPDATE_RECEIPTPREFIX_SUCCESS_RESET =
  "UPDATE_RECEIPTPREFIX_SUCCESS_RESET";
export const UPDATE_RECEIPTPREFIX_FAIL = "UPDATE_CourseDuration_FAIL";

export const ALL_RECEIPTPREFIX_REQUEST = " ALL_RECEIPTPREFIX_REQUEST";
export const ALL_RECEIPTPREFIX_SUCCESS = " ALL_RECEIPTPREFIX_SUCCESS";
export const ALL_RECEIPTPREFIX_FAIL = " ALL_RECEIPTPREFIX_FAIL";

export const DELETE_RECEIPTPREFIX_REQUEST = "DELETE_RECEIPTPREFIX_REQUEST";
export const DELETE_RECEIPTPREFIX_SUCCESS = "DELETE_RECEIPTPREFIX_SUCCESS";
export const DELETE_RECEIPTPREFIX_FAIL = "DELETE_RECEIPTPREFIX_FAIL";



export const ALL_RECEIPTDATA_REQUEST = " ALL_RECEIPTDATA_REQUEST";
export const ALL_RECEIPTDATA_SUCCESS = " ALL_RECEIPTDATA_SUCCESS";
export const ALL_RECEIPTDATA_FAIL = " ALL_RECEIPTDATA_FAIL";

export const GET_SESSION_REQUEST = "GET_SESSION_REQUEST";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_SESSION_FAIL = "GET_SESSION_FAIL";

export const GET_SECTION_REQUEST = "GET_SECTION__REQUEST";
export const GET_SECTION__SUCCESS = "GET_SECTION__SUCCESS";
export const GET_SECTION__FAIL = "GET_SECTION__FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
