export const GET_ASSETTYPE_REQUEST = "GET_ASSETTYPE_REQUEST";
export const GET_ASSETTYPE_SUCCESS = "GET_ASSETTYPE_SUCCESS";
export const GET_ASSETTYPE_FAIL = "GET_ASSETTYPE_FAIL";

export const GET_ASSET_REQUEST = "GET_ASSET_REQUEST";
export const GET_ASSET_SUCCESS = "GET_ASSET_SUCCESS";
export const GET_ASSET_FAIL = "GET_ASSET_FAIL";

export const GET_EXPENSESTYPE_REQUEST = "GET_EXPENSESTYPE_REQUEST";
export const GET_EXPENSESTYPE_SUCCESS = "GET_EXPENSESTYPE_SUCCESS";
export const GET_EXPENSESTYPE_FAIL = "GET_EXPENSESTYPE_FAIL";

export const GET_EXPENSES_REQUEST = "GET_EXPENSES_REQUEST";
export const GET_EXPENSES_SUCCESS = "GET_EXPENSES_SUCCESS";
export const GET_EXPENSES_FAIL = "GET_EXPENSES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
