export const GET_ROOM_CATEGORY_REQUEST = "GET_ROOM_CATEGORY_REQUEST";
export const GET_ROOM_CATEGORY_SUCCESS = "GET_ROOM_CATEGORY_SUCCESS";
export const GET_ROOM_CATEGORY_FAIL = "GET_ROOM_CATEGORY_FAIL";

export const GET_ROOM_FACILITY_REQUEST = "GET_ROOM_FACILITY_REQUEST";
export const GET_ROOM_FACILITY_SUCCESS = "GET_ROOM_FACILITY_SUCCESS";
export const GET_ROOM_FACILITY_FAIL = "GET_ROOM_FACILITY_FAIL";

export const GET_HOSTEL_REQUEST = "GET_HOSTEL_REQUEST";
export const GET_HOSTEL_SUCCESS = "GET_HOSTEL_SUCCESS";
export const GET_HOSTEL_FAIL = "GET_HOSTEL_FAIL";

export const GET_ROOM_REQUEST = "GET_ROOM_REQUEST";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const GET_ROOM_FAIL = "GET_ROOM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
