export const GET_PAYROLL_REQUEST = "GET_PAYROLL_REQUEST";
export const GET_PAYROLL_SUCCESS = "GET_PAYROLL_SUCCESS";
export const GET_PAYROLL_FAIL = "GET_PAYROLL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";