export const ALL_ENQUIRY_REQUEST = "ALL_ENQUIRY_REQUEST";
export const ALL_ENQUIRY_SUCCESS = "ALL_ENQUIRY_SUCCESS";
export const ALL_ENQUIRY_FAIL = "ALL_ENQUIRY_FAIL";

export const ALL_COACHINGMONTHLYFEE_REQUEST = "ALL_COACHINGMONTHLYFEE_REQUEST";
export const ALL_COACHINGMONTHLYFEE_SUCCESS = "ALL_COACHINGMONTHLYFEE_SUCCESS";
export const ALL_COACHINGMONTHLYFEE_FAIL = "ALL_COACHINGMONTHLYFEE_FAIL";



export const CLEAR_ERRORS ="CLEAR_ERRORS";