export const ALL_ENQUIRY_REQUEST = "ALL_ENQUIRY_REQUEST";
export const ALL_ENQUIRY_SUCCESS = "ALL_ENQUIRY_SUCCESS";
export const ALL_ENQUIRY_FAIL = "ALL_ENQUIRY_FAIL";

export const ALL_STUDENT_RESULT_REQUEST = "ALL_STUDENT_RESULT_REQUEST";
export const ALL_STUDENT_RESULT_SUCCESS = "ALL_STUDENT_RESULT_SUCCESS";
export const ALL_STUDENT_RESULT_FAIL = "ALL_STUDENT_RESULT_FAIL";



export const CLEAR_ERRORS ="CLEAR_ERRORS";