export const GET_VEHICLE_TYPE_REQUEST = "GET_VEHICLE_TYPE_REQUEST";
export const GET_VEHICLE_TYPE_SUCCESS = "GET_VEHICLE_TYPE_SUCCESS";
export const GET_VEHICLE_TYPE_FAIL = "GET_VEHICLE_TYPE_FAIL";

export const GET_VEHICLEDETAILS_REQUEST = "GET_VEHICLEDETAILS_REQUEST";
export const GET_VEHICLEDETAILS_SUCCESS = "GET_VEHICLEDETAILS_SUCCESS";
export const GET_VEHICLEDETAILS_FAIL = "GET_VEHICLEDETAILS_FAIL";

export const GET_ROUTES_REQUEST = "GET_ROUTES_REQUEST";
export const GET_ROUTES_SUCCESS = "GET_ROUTES_SUCCESS";
export const GET_ROUTES_FAIL = "GET_ROUTES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
